=== slacker247/GPDA/Protege-2000/evidence.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT evidence (SystemClasses*, STANDARD-CLASS*, SLOT*, Evidence*, PAL-CONSTRAINT*)>
<!ELEMENT SystemClasses (#PCDATA)>
<!ATTLIST SystemClasses
	id ID #IMPLIED
>
<!ELEMENT NAME (#PCDATA)>
<!ATTLIST NAME
	id ID #IMPLIED
>
<!ELEMENT ROLE (#PCDATA)>
<!ATTLIST ROLE
	id ID #IMPLIED
>
<!ELEMENT DOCUMENTATION (#PCDATA)>
<!ATTLIST DOCUMENTATION
	id ID #IMPLIED
>
<!ELEMENT CONSTRAINTS EMPTY>
<!ATTLIST CONSTRAINTS
	refid CDATA #IMPLIED
>
<!ELEMENT Instances (#PCDATA)>
<!ATTLIST Instances
	id ID #IMPLIED
>
<!ATTLIST Instances
	refid IDREFS #IMPLIED
>
<!ELEMENT Subclasses (#PCDATA)>
<!ATTLIST Subclasses
	id ID #IMPLIED
>
<!ATTLIST Subclasses
	refid IDREFS #IMPLIED
>
<!ELEMENT SlotValues (#PCDATA)>
<!ATTLIST SlotValues
	id ID #IMPLIED
>
<!ELEMENT SlotDefaultValue (#PCDATA)>
<!ATTLIST SlotDefaultValue
	id ID #IMPLIED
>
<!ELEMENT SlotType (#PCDATA)>
<!ATTLIST SlotType
	id ID #IMPLIED
>
<!ELEMENT SlotMinCard (#PCDATA)>
<!ATTLIST SlotMinCard
	id ID #IMPLIED
>
<!ELEMENT SlotMaxCard (#PCDATA)>
<!ATTLIST SlotMaxCard
	id ID #IMPLIED
>
<!ELEMENT SlotAllowedClass (#PCDATA)>
<!ATTLIST SlotAllowedClass
	id ID #IMPLIED
>
<!ELEMENT SlotMinimum (#PCDATA)>
<!ATTLIST SlotMinimum
	id ID #IMPLIED
>
<!ELEMENT SlotMaximum (#PCDATA)>
<!ATTLIST SlotMaximum
	id ID #IMPLIED
>
<!ELEMENT SlotDocumentation (#PCDATA)>
<!ATTLIST SlotDocumentation
	id ID #IMPLIED
>
<!ELEMENT SlotInverseSlot (#PCDATA)>
<!ATTLIST SlotInverseSlot
	id ID #IMPLIED
>
<!ELEMENT SlotConstraints (#PCDATA)>
<!ATTLIST SlotConstraints
	id ID #IMPLIED
>
<!ELEMENT SlotAllowedParents (#PCDATA)>
<!ATTLIST SlotAllowedParents
	id ID #IMPLIED
>
<!ELEMENT SlotSubslots (#PCDATA)>
<!ATTLIST SlotSubslots
	id ID #IMPLIED
>
<!ELEMENT TemplateSlots (#PCDATA)>
<!ATTLIST TemplateSlots
	id IDREFS #IMPLIED
>
<!ELEMENT SLOT (SlotType?, SlotAllowedClass*, SlotConstraints*, SlotDefaultValue*, SlotDocumentation*, SlotInverseSlot*, SlotMaxCard*, SlotMaximum?, SlotMinCard*, SlotMinimum?, SlotSubslots*, SlotValues*, SlotAllowedParents*)>
<!ATTLIST SLOT
	id ID #IMPLIED
>
<!ELEMENT OverriddenSLOT (SlotType?, SlotAllowedClass*, SlotConstraints*, SlotDefaultValue*, SlotDocumentation*, SlotInverseSlot*, SlotMaxCard*, SlotMaximum?, SlotMinCard*, SlotMinimum?, SlotSubslots*, SlotValues*, SlotAllowedParents*)>
<!ATTLIST OverriddenSLOT
	id IDREFS #IMPLIED
>
<!ELEMENT STANDARD-CLASS (CONSTRAINTS*, DOCUMENTATION*, NAME*, ROLE*, TemplateSlot*, OverriddenSLOT*)>
<!ATTLIST STANDARD-CLASS
	id ID #IMPLIED
	superclass_id IDREFS #IMPLIED
>
<!ELEMENT Evidence (Arg-1?, Arg-2?, Arg-3?, Belief?, Description?, Disbelief?, Dur-Unit?, Duration?, External-Filename?, External_Level?, External_Node?, Level?, Mission-Domain?, Node?, Source?, Time?, Time-Unit?, Type?)>
<!ATTLIST Evidence
	id ID #IMPLIED
	superclass_id IDREFS #IMPLIED
>
<!ELEMENT Arg-1 (#PCDATA)>
<!ATTLIST Arg-1
	id ID #IMPLIED
>
<!ELEMENT Arg-2 (#PCDATA)>
<!ATTLIST Arg-2
	id ID #IMPLIED
>
<!ELEMENT Arg-3 (#PCDATA)>
<!ATTLIST Arg-3
	id ID #IMPLIED
>
<!ELEMENT Belief (#PCDATA)>
<!ATTLIST Belief
	id ID #IMPLIED
>
<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description
	id ID #IMPLIED
>
<!ELEMENT Disbelief (#PCDATA)>
<!ATTLIST Disbelief
	id ID #IMPLIED
>
<!ELEMENT Dur-Unit (#PCDATA)>
<!ATTLIST Dur-Unit
	id ID #IMPLIED
>
<!ELEMENT Duration (#PCDATA)>
<!ATTLIST Duration
	id ID #IMPLIED
>
<!ELEMENT External-Filename (#PCDATA)>
<!ATTLIST External-Filename
	id ID #IMPLIED
>
<!ELEMENT External_Level (#PCDATA)>
<!ATTLIST External_Level
	id ID #IMPLIED
>
<!ELEMENT External_Node (#PCDATA)>
<!ATTLIST External_Node
	id ID #IMPLIED
>
<!ELEMENT Level (#PCDATA)>
<!ATTLIST Level
	id ID #IMPLIED
>
<!ELEMENT Mission-Domain (#PCDATA)>
<!ATTLIST Mission-Domain
	id ID #IMPLIED
>
<!ELEMENT Node (#PCDATA)>
<!ATTLIST Node
	id ID #IMPLIED
>
<!ELEMENT Source (#PCDATA)>
<!ATTLIST Source
	id ID #IMPLIED
>
<!ELEMENT Time (#PCDATA)>
<!ATTLIST Time
	id ID #IMPLIED
>
<!ELEMENT Time-Unit (#PCDATA)>
<!ATTLIST Time-Unit
	id ID #IMPLIED
>
<!ELEMENT Type (#PCDATA)>
<!ATTLIST Type
	id ID #IMPLIED
>

=== slacker247/GPDA/Protege-2000/evidence.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE evidence SYSTEM "file:////home/dre/Protege-2000/evidence.dtd">
<evidence>
	<SystemClasses id="STANDARD-CLASS">
	</SystemClasses>
	<SystemClasses id="THING">
	</SystemClasses>
	<SystemClasses id="PAL-CONSTRAINT">
	</SystemClasses>
	<STANDARD-CLASS id="Evidence" superclass_id="THING">
		<NAME>Evidence</NAME>
		<ROLE>Concrete</ROLE>
		<TemplateSlot id="Arg-1"/>
		<TemplateSlot id="Arg-2"/>
		<TemplateSlot id="Arg-3"/>
		<TemplateSlot id="Belief"/>
		<TemplateSlot id="Description"/>
		<TemplateSlot id="Disbelief"/>
		<TemplateSlot id="Dur-Unit"/>
		<TemplateSlot id="Duration"/>
		<TemplateSlot id="External-Filename"/>
		<TemplateSlot id="External_Level"/>
		<TemplateSlot id="External_Node"/>
		<TemplateSlot id="Level"/>
		<TemplateSlot id="Mission-Domain"/>
		<TemplateSlot id="Node"/>
		<TemplateSlot id="Source"/>
		<TemplateSlot id="Time"/>
		<TemplateSlot id="Time-Unit"/>
		<TemplateSlot id="Type"/>
	</STANDARD-CLASS>
	<SLOT id="Arg-1">
		<SlotType>STRING</SlotType>
		<SlotDocumentation>Argument 1</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Arg-2">
		<SlotType>STRING</SlotType>
		<SlotDocumentation>Argument 2</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Arg-3">
		<SlotType>STRING</SlotType>
		<SlotDocumentation>Argument 3</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Belief">
		<SlotType>FLOAT</SlotType>
		<SlotDocumentation>Percent Confidence</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMaximum>1.0</SlotMaximum>
		<SlotMinCard>0</SlotMinCard>
		<SlotMinimum>0.0</SlotMinimum>
	</SLOT>
	<SLOT id="Description">
		<SlotType>STRING</SlotType>
		<SlotDocumentation>Source Description</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Disbelief">
		<SlotType>FLOAT</SlotType>
		<SlotDocumentation>Amount Disbelief</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMaximum>1.0</SlotMaximum>
		<SlotMinCard>0</SlotMinCard>
		<SlotMinimum>0.0</SlotMinimum>
	</SLOT>
	<SLOT id="Dur-Unit">
		<SlotType>STRING</SlotType>
		<SlotDocumentation>Duration Time Unit</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Duration">
		<SlotType>FLOAT</SlotType>
		<SlotDocumentation>Evidence Duration</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="External-Filename">
		<SlotType>STRING</SlotType>
		<SlotDefaultValue>None</SlotDefaultValue>
		<SlotDocumentation>External file name</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="External_Level">
		<SlotType>INTEGER</SlotType>
		<SlotDocumentation>External level number</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="External_Node">
		<SlotType>INTEGER</SlotType>
		<SlotDocumentation>External node number</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Level">
		<SlotType>INTEGER</SlotType>
		<SlotDocumentation>Network Level</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Mission-Domain">
		<SlotType>STRING</SlotType>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Node">
		<SlotType>INTEGER</SlotType>
		<SlotDocumentation>Node number</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Source">
		<SlotType>STRING</SlotType>
		<SlotDocumentation>Evidence Source</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Time">
		<SlotType>FLOAT</SlotType>
		<SlotDocumentation>Evidence Time</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Time-Unit">
		<SlotType>STRING</SlotType>
		<SlotDocumentation>Evidence time units</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<SLOT id="Type">
		<SlotType>INTEGER</SlotType>
		<SlotDocumentation>0=Source,1=Override,2=External</SlotDocumentation>
		<SlotMaxCard>1</SlotMaxCard>
		<SlotMinCard>0</SlotMinCard>
	</SLOT>
	<Evidence id="evidence_00018">
		<Arg-1>18.465</Arg-1>
		<Arg-2>26.285</Arg-2>
		<Arg-3>Sat</Arg-3>
		<Belief>0.6</Belief>
		<Description>F117/Mig</Description>
		<Disbelief>0.25</Disbelief>
		<Dur-Unit>H</Dur-Unit>
		<Duration>0.6</Duration>
		<External-Filename>None</External-Filename>
		<External-Filename>None</External-Filename>
		<External_Level>0</External_Level>
		<External_Node>0</External_Node>
		<Level>1</Level>
		<Mission-Domain>IW-DCI</Mission-Domain>
		<Node>1</Node>
		<Source>Site</Source>
		<Time>26.3</Time>
		<Time-Unit>M</Time-Unit>
		<Type>0</Type>
	</Evidence>
</evidence>
