=== slacker247/GPDA/Aries/Protege-New/Oil-2.2/tmp/fact.dtd
<!ELEMENT KNOWLEDGEBASE (DEFCONCEPT|DEFROLE|IMPLIESC|EQUALC|IMPLIESR|EQUALR|TRANSITIVE|FUNCTIONAL)*>

<!ELEMENT DEFCONCEPT EMPTY>
<!ATTLIST DEFCONCEPT NAME CDATA #REQUIRED>

<!ELEMENT DEFROLE EMPTY>
<!ATTLIST DEFROLE NAME CDATA #REQUIRED>

<!ELEMENT IMPLIESC (CONCEPT, CONCEPT)>

<!ELEMENT EQUALC (CONCEPT, CONCEPT)>

<!ELEMENT IMPLIESR (ROLE, ROLE)>

<!ELEMENT EQUALR (ROLE, ROLE)>

<!ELEMENT TRANSITIVE (ROLE)>

<!ELEMENT FUNCTIONAL (ROLE)>

<!ELEMENT CONCEPT (PRIMITIVE|TOP|BOTTOM|AND|OR|NOT|SOME|ALL|ATMOST|ATLEAST)>
<!ELEMENT ROLE (PRIMROLE|INVROLE)>

<!ELEMENT PRIMITIVE EMPTY>
<!ATTLIST PRIMITIVE NAME CDATA #REQUIRED>

<!ELEMENT TOP EMPTY>

<!ELEMENT BOTTOM EMPTY>

<!ELEMENT AND (PRIMITIVE|TOP|BOTTOM|AND|OR|NOT|SOME|ALL|ATMOST|ATLEAST)+>

<!ELEMENT OR (PRIMITIVE|TOP|BOTTOM|AND|OR|NOT|SOME|ALL|ATMOST|ATLEAST)+>

<!ELEMENT NOT (PRIMITIVE|TOP|BOTTOM|AND|OR|NOT|SOME|ALL|ATMOST|ATLEAST)>

<!ELEMENT SOME ((PRIMROLE|INVROLE),
                (PRIMITIVE|TOP|BOTTOM|AND|OR|NOT|SOME|ALL|ATMOST|ATLEAST))>

<!ELEMENT ALL ((PRIMROLE|INVROLE),
               (PRIMITIVE|TOP|BOTTOM|AND|OR|NOT|SOME|ALL|ATMOST|ATLEAST))>

<!ELEMENT ATLEAST ((PRIMROLE|INVROLE),
                   (PRIMITIVE|TOP|BOTTOM|AND|OR|NOT|SOME|ALL|ATMOST|ATLEAST))>
<!ATTLIST ATLEAST NUM CDATA #REQUIRED>

<!ELEMENT ATMOST ((PRIMROLE|INVROLE),
                  (PRIMITIVE|TOP|BOTTOM|AND|OR|NOT|SOME|ALL|ATMOST|ATLEAST))>
<!ATTLIST ATMOST NUM CDATA #REQUIRED>

<!ELEMENT PRIMROLE EMPTY>
<!ATTLIST PRIMROLE NAME CDATA #REQUIRED>

<!ELEMENT INVROLE (PRIMROLE|INVROLE)>

=== slacker247/GPDA/Protege-2000/FaCT/tboxes/xml/people.xml
<?xml version="1.0"?>
<!DOCTYPE KNOWLEDGEBASE SYSTEM "fact.dtd">
<KNOWLEDGEBASE>
<DEFCONCEPT NAME="PERSON"/>
<DEFCONCEPT NAME="MAN"/>
<DEFCONCEPT NAME="WOMAN"/>
<DEFCONCEPT NAME="ANIMAL"/>
<DEFCONCEPT NAME="DOG"/>
<DEFCONCEPT NAME="CAT"/>
<DEFCONCEPT NAME="AGE"/>
<DEFCONCEPT NAME="YOUNG"/>
<DEFCONCEPT NAME="OLD"/>

<DEFROLE NAME="hasAge"/>
<DEFROLE NAME="hasPet"/>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="MAN"/>
  </CONCEPT>
  <CONCEPT>
    <PRIMITIVE NAME="PERSON"/>
  </CONCEPT>
</IMPLIESC>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="WOMAN"/>
  </CONCEPT>
  <CONCEPT>
    <PRIMITIVE NAME="PERSON"/>
  </CONCEPT>
</IMPLIESC>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="WOMAN"/>
  </CONCEPT>
  <CONCEPT>
    <NOT>
      <PRIMITIVE NAME="MAN"/>
    </NOT>
  </CONCEPT>
</IMPLIESC>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="MAN"/>
  </CONCEPT>
  <CONCEPT>
    <NOT>
      <PRIMITIVE NAME="WOMAN"/>
    </NOT>
  </CONCEPT>
</IMPLIESC>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="DOG"/>
  </CONCEPT>
  <CONCEPT>
    <PRIMITIVE NAME="ANIMAL"/>
  </CONCEPT>
</IMPLIESC>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="CAT"/>
  </CONCEPT>
  <CONCEPT>
    <PRIMITIVE NAME="ANIMAL"/>
  </CONCEPT>
</IMPLIESC>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="DOG"/>
  </CONCEPT>
  <CONCEPT>
    <NOT>
      <PRIMITIVE NAME="CAT"/>
    </NOT>
  </CONCEPT>
</IMPLIESC>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="OLD"/>
  </CONCEPT>
  <CONCEPT>
    <NOT>
      <PRIMITIVE NAME="YOUNG"/>
    </NOT>
  </CONCEPT>
</IMPLIESC>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="YOUNG"/>
  </CONCEPT>
  <CONCEPT>
    <PRIMITIVE NAME="AGE"/>
  </CONCEPT>
</IMPLIESC>

<IMPLIESC>
  <CONCEPT>
    <PRIMITIVE NAME="OLD"/>
  </CONCEPT>
  <CONCEPT>
    <PRIMITIVE NAME="AGE"/>
  </CONCEPT>
</IMPLIESC>

<DEFCONCEPT NAME="OLDLADY"/>

<EQUALC>
  <CONCEPT>
    <PRIMITIVE NAME="OLDLADY"/>
  </CONCEPT>
  <CONCEPT>
    <AND>
      <PRIMITIVE NAME="WOMAN"/>
      <ALL>
        <PRIMROLE NAME="hasAge"/>
        <PRIMITIVE NAME="OLD"/>
      </ALL>
      <ALL>
        <PRIMROLE NAME="hasPet"/>
        <PRIMITIVE NAME="CAT"/>
      </ALL>
      <SOME>
        <PRIMROLE NAME="hasPet"/>
	<TOP/>
      </SOME>
    </AND>
  </CONCEPT>
</EQUALC>

<DEFCONCEPT NAME="DOGOWNER"/>
<EQUALC>
  <CONCEPT>
    <PRIMITIVE NAME="DOGOWNER"/>
  </CONCEPT>
  <CONCEPT>
    <AND>
      <PRIMITIVE NAME="PERSON"/>
      <SOME>
        <PRIMROLE NAME="hasPet"/>
        <PRIMITIVE NAME="DOG"/>
      </SOME>
    </AND>
  </CONCEPT>
</EQUALC>

<DEFCONCEPT NAME="CATOWNER"/>
<EQUALC>
  <CONCEPT>
    <PRIMITIVE NAME="CATOWNER"/>
  </CONCEPT>
  <CONCEPT>
    <AND>
      <PRIMITIVE NAME="PERSON"/>
      <SOME>
        <PRIMROLE NAME="hasPet"/>
        <PRIMITIVE NAME="CAT"/>
      </SOME>
    </AND>
  </CONCEPT>
</EQUALC>

<DEFCONCEPT NAME="PETOWNER"/>
<EQUALC>
  <CONCEPT>
    <PRIMITIVE NAME="PETOWNER"/>
  </CONCEPT>
  <CONCEPT>
    <AND>
      <PRIMITIVE NAME="PERSON"/>
      <SOME>
        <PRIMROLE NAME="hasPet"/>
        <PRIMITIVE NAME="ANIMAL"/>
      </SOME>
    </AND>
  </CONCEPT>
</EQUALC>

<DEFCONCEPT NAME="CATHATER"/>
<EQUALC>
  <CONCEPT>
    <PRIMITIVE NAME="CATHATER"/>
  </CONCEPT>
  <CONCEPT>
    <AND>
      <PRIMITIVE NAME="PERSON"/>
      <ALL>
        <PRIMROLE NAME="hasPet"/>
	<NOT>
          <PRIMITIVE NAME="CAT"/>
        </NOT>
      </ALL>
    </AND>
  </CONCEPT>
</EQUALC>

<DEFCONCEPT NAME="DOGHATER"/>
<EQUALC>
  <CONCEPT>
    <PRIMITIVE NAME="DOGHATER"/>
  </CONCEPT>
  <CONCEPT>
    <AND>
      <PRIMITIVE NAME="PERSON"/>
      <ALL>
        <PRIMROLE NAME="hasPet"/>
	<NOT>
          <PRIMITIVE NAME="DOG"/>
        </NOT>
      </ALL>
    </AND>
  </CONCEPT>
</EQUALC>

<DEFCONCEPT NAME="CATLIKER"/>
<EQUALC>
  <CONCEPT>
    <PRIMITIVE NAME="CATLIKER"/>
  </CONCEPT>
  <CONCEPT>
    <NOT>
      <PRIMITIVE NAME="CATHATER"/>
    </NOT>
  </CONCEPT>
</EQUALC>

</KNOWLEDGEBASE>
